# Generated by Django 6.0.3 on 2026-03-31 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('whatsapp_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICopilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('system_prompt', models.TextField(help_text='System instruction for the AI bot')),
                ('model', models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gpt-4o-mini', 'GPT-4o Mini'), ('gemini-pro', 'Gemini Pro')], default='gpt-4o-mini', max_length=20)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=500)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_reply', models.BooleanField(default=True)),
                ('business_hours_only', models.BooleanField(default=False)),
                ('greeting_message', models.TextField(blank=True)),
                ('fallback_message', models.TextField(blank=True, default='I will connect you with our team shortly.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilots', to='accounts.tenant')),
                ('wa_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp_integration.whatsappconfig')),
            ],
            options={
                'db_table': 'ai_copilots',
            },
        ),
        migrations.CreateModel(
            name='CopilotTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('copilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_data', to='copilots.aicopilot')),
            ],
            options={
                'db_table': 'copilot_training_data',
            },
        ),
    ]
