# Generated by Django 6.0.3 on 2026-03-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee'), ('sales', 'Sales'), ('support', 'Support'), ('viewer', 'Viewer')], default='employee', max_length=20),
        ),
    ]
