# Generated by Django 6.0.3 on 2026-03-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
